{{- if .Values.k8sgpt.enabled }}
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: {{ .Values.k8sgpt.name }}
  namespace: {{ .Values.k8sgpt.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
spec:
  ai:
    enabled: {{ .Values.k8sgpt.ai.enabled }}
    model: {{ .Values.k8sgpt.ai.model | quote }}
    backend: {{ .Values.k8sgpt.ai.backend | quote }}
{{- if .Values.k8sgpt.ai.baseUrl }}
    baseUrl: {{ .Values.k8sgpt.ai.baseUrl | quote }}
{{- end }}
    secret:
      name: {{ .Values.k8sgpt.ai.secret.name }}
      key: {{ .Values.k8sgpt.ai.secret.key }}
{{- if .Values.k8sgpt.ai.autoRemediation }}
    autoRemediation:
      enabled: {{ .Values.k8sgpt.ai.autoRemediation.enabled }}
{{- if .Values.k8sgpt.ai.autoRemediation.resources }}
      resources:
{{- range .Values.k8sgpt.ai.autoRemediation.resources }}
        - {{ . }}
{{- end }}
{{- end }}
{{- end }}
  noCache: {{ .Values.k8sgpt.noCache }}
  version: {{ .Values.k8sgpt.version }}
{{- if .Values.k8sgpt.analysis }}
  analysis:
    interval: {{ .Values.k8sgpt.analysis.interval | quote }}
{{- end }}
{{- end }}


